### ISSUE TITLE
Feedback Score

### ISSUE THREAD

**Issue by tjoye20** [mousaayoubi/prj-rev-bwfs-dasmoto#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 3 - Meets Expectations
* _Comment(s):_ All the elements for each section should be inside of the `div` tag for that section. For example, all your `h3` and `p` elements should be inside of the `div`. 
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4 - Exceeds Expectations
 
### Overall Score: 15/16
Great work on this project, Mousa. You have a good understanding of HTML and CSS basics, just keep in mind my comment on Criteria 3. Other than that, looking forward to your other projects!

**Comment by mousaayoubi** [comment]
Great! Thank you for the review.
